// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package boltgo

type Payments struct {
	LoggedIn *LoggedIn
	Guest    *Guest

	sdkConfiguration sdkConfiguration
}

func newPayments(sdkConfig sdkConfiguration) *Payments {
	return &Payments{
		sdkConfiguration: sdkConfig,
		LoggedIn:         newLoggedIn(sdkConfig),
		Guest:            newGuest(sdkConfig),
	}
}
