// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type AccountAddressEditRequest struct {
	// The ID of the address to edit
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The publicly shareable identifier used to identify your Bolt merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// A unique identifier for a shopper's device, generated by Bolt. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics.
	XMerchantClientID string                         `header:"style=simple,explode=false,name=X-Merchant-Client-Id"`
	AddressListing    components.AddressListingInput `request:"mediaType=application/json"`
}

func (o *AccountAddressEditRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AccountAddressEditRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *AccountAddressEditRequest) GetXMerchantClientID() string {
	if o == nil {
		return ""
	}
	return o.XMerchantClientID
}

func (o *AccountAddressEditRequest) GetAddressListing() components.AddressListingInput {
	if o == nil {
		return components.AddressListingInput{}
	}
	return o.AddressListing
}

type AccountAddressEditResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The address was successfully edited
	AddressListing *components.AddressListing
}

func (o *AccountAddressEditResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountAddressEditResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountAddressEditResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountAddressEditResponse) GetAddressListing() *components.AddressListing {
	if o == nil {
		return nil
	}
	return o.AddressListing
}
