// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type GuestPaymentsActionSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *GuestPaymentsActionSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type GuestPaymentsActionRequest struct {
	// The ID of the guest payment to operate on
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The publicly shareable identifier used to identify your Bolt merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// A unique identifier for a shopper's device, generated by Bolt. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics.
	XMerchantClientID    string                          `header:"style=simple,explode=false,name=X-Merchant-Client-Id"`
	PaymentActionRequest components.PaymentActionRequest `request:"mediaType=application/json"`
}

func (o *GuestPaymentsActionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GuestPaymentsActionRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *GuestPaymentsActionRequest) GetXMerchantClientID() string {
	if o == nil {
		return ""
	}
	return o.XMerchantClientID
}

func (o *GuestPaymentsActionRequest) GetPaymentActionRequest() components.PaymentActionRequest {
	if o == nil {
		return components.PaymentActionRequest{}
	}
	return o.PaymentActionRequest
}

type GuestPaymentsActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The action was successfully applied to the pending guest payment
	PaymentResponse *components.PaymentResponse
}

func (o *GuestPaymentsActionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GuestPaymentsActionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GuestPaymentsActionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GuestPaymentsActionResponse) GetPaymentResponse() *components.PaymentResponse {
	if o == nil {
		return nil
	}
	return o.PaymentResponse
}

func (o *GuestPaymentsActionResponse) GetPaymentResponseFinalized() *components.PaymentResponseFinalized {
	if v := o.GetPaymentResponse(); v != nil {
		return v.PaymentResponseFinalized
	}
	return nil
}

func (o *GuestPaymentsActionResponse) GetPaymentResponsePending() *components.PaymentResponsePending {
	if v := o.GetPaymentResponse(); v != nil {
		return v.PaymentResponsePending
	}
	return nil
}
