// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type OauthGetTokenRequest struct {
	// A unique identifier for a shopper's device, generated by Bolt. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics.
	XMerchantClientID string                  `header:"style=simple,explode=false,name=X-Merchant-Client-Id"`
	TokenRequest      components.TokenRequest `request:"mediaType=application/x-www-form-urlencoded"`
}

func (o *OauthGetTokenRequest) GetXMerchantClientID() string {
	if o == nil {
		return ""
	}
	return o.XMerchantClientID
}

func (o *OauthGetTokenRequest) GetTokenRequest() components.TokenRequest {
	if o == nil {
		return components.TokenRequest{}
	}
	return o.TokenRequest
}

type OauthGetTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Access token is successfully fetched
	GetAccessTokenResponse *components.GetAccessTokenResponse
}

func (o *OauthGetTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OauthGetTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OauthGetTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OauthGetTokenResponse) GetGetAccessTokenResponse() *components.GetAccessTokenResponse {
	if o == nil {
		return nil
	}
	return o.GetAccessTokenResponse
}
