// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type OrdersCreateSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *OrdersCreateSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type OrdersCreateRequest struct {
	// The publicly shareable identifier used to identify your Bolt merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// A unique identifier for a shopper's device, generated by Bolt. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics.
	XMerchantClientID string           `header:"style=simple,explode=false,name=X-Merchant-Client-Id"`
	Order             components.Order `request:"mediaType=application/json"`
}

func (o *OrdersCreateRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *OrdersCreateRequest) GetXMerchantClientID() string {
	if o == nil {
		return ""
	}
	return o.XMerchantClientID
}

func (o *OrdersCreateRequest) GetOrder() components.Order {
	if o == nil {
		return components.Order{}
	}
	return o.Order
}

type OrdersCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The order was successfuly created
	OrderResponse *components.OrderResponse
}

func (o *OrdersCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OrdersCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OrdersCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OrdersCreateResponse) GetOrderResponse() *components.OrderResponse {
	if o == nil {
		return nil
	}
	return o.OrderResponse
}
