// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type PaymentsActionRequest struct {
	// The ID of the payment to operate on
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey      string                          `header:"style=simple,explode=false,name=X-Publishable-Key"`
	PaymentActionRequest components.PaymentActionRequest `request:"mediaType=application/json"`
}

func (o *PaymentsActionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PaymentsActionRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *PaymentsActionRequest) GetPaymentActionRequest() components.PaymentActionRequest {
	if o == nil {
		return components.PaymentActionRequest{}
	}
	return o.PaymentActionRequest
}

type PaymentsActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The action was successfully applied to the pending payment
	PaymentResponse *components.PaymentResponse
}

func (o *PaymentsActionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PaymentsActionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PaymentsActionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PaymentsActionResponse) GetPaymentResponse() *components.PaymentResponse {
	if o == nil {
		return nil
	}
	return o.PaymentResponse
}

func (o *PaymentsActionResponse) GetPaymentResponseFinalized() *components.PaymentResponseFinalized {
	if v := o.GetPaymentResponse(); v != nil {
		return v.PaymentResponseFinalized
	}
	return nil
}

func (o *PaymentsActionResponse) GetPaymentResponsePending() *components.PaymentResponsePending {
	if v := o.GetPaymentResponse(); v != nil {
		return v.PaymentResponsePending
	}
	return nil
}
