// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type TestingAccountCreateSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *TestingAccountCreateSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type TestingAccountCreateRequest struct {
	// The publicly shareable identifier used to identify your Bolt merchant division.
	XPublishableKey         string                             `header:"style=simple,explode=false,name=X-Publishable-Key"`
	AccountTestCreationData components.AccountTestCreationData `request:"mediaType=application/json"`
}

func (o *TestingAccountCreateRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *TestingAccountCreateRequest) GetAccountTestCreationData() components.AccountTestCreationData {
	if o == nil {
		return components.AccountTestCreationData{}
	}
	return o.AccountTestCreationData
}

type TestingAccountCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The account was successfully created
	AccountTestCreationData *components.AccountTestCreationDataOutput
}

func (o *TestingAccountCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TestingAccountCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TestingAccountCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TestingAccountCreateResponse) GetAccountTestCreationData() *components.AccountTestCreationDataOutput {
	if o == nil {
		return nil
	}
	return o.AccountTestCreationData
}
