// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// AccountAddressEditResponseBody - The address is invalid and cannot be added, or some other error has occurred
type AccountAddressEditResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &AccountAddressEditResponseBody{}

func (e *AccountAddressEditResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
