// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// GuestPaymentsInitializeResponseBody - The payment operation cannot complete
type GuestPaymentsInitializeResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GuestPaymentsInitializeResponseBody{}

func (e *GuestPaymentsInitializeResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
