// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/BoltApp/bolt-go/internal/utils"
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type GuestPaymentsUpdateResponseBodyType string

const (
	GuestPaymentsUpdateResponseBodyTypeGenericError GuestPaymentsUpdateResponseBodyType = "generic-error"
	GuestPaymentsUpdateResponseBodyTypeFieldError   GuestPaymentsUpdateResponseBodyType = "field-error"
)

// GuestPaymentsUpdateResponseBody - An error has occurred, and further details are contained in the response
type GuestPaymentsUpdateResponseBody struct {
	GenericError *components.GenericError
	FieldError   *components.FieldError

	Type GuestPaymentsUpdateResponseBodyType

	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GuestPaymentsUpdateResponseBody{}

func CreateGuestPaymentsUpdateResponseBodyGenericError(genericError components.GenericError) GuestPaymentsUpdateResponseBody {
	typ := GuestPaymentsUpdateResponseBodyTypeGenericError

	return GuestPaymentsUpdateResponseBody{
		GenericError: &genericError,
		Type:         typ,
	}
}

func CreateGuestPaymentsUpdateResponseBodyFieldError(fieldError components.FieldError) GuestPaymentsUpdateResponseBody {
	typ := GuestPaymentsUpdateResponseBodyTypeFieldError

	return GuestPaymentsUpdateResponseBody{
		FieldError: &fieldError,
		Type:       typ,
	}
}

func (u *GuestPaymentsUpdateResponseBody) UnmarshalJSON(data []byte) error {

	var genericError components.GenericError = components.GenericError{}
	if err := utils.UnmarshalJSON(data, &genericError, "", true, true); err == nil {
		u.GenericError = &genericError
		u.Type = GuestPaymentsUpdateResponseBodyTypeGenericError
		return nil
	}

	var fieldError components.FieldError = components.FieldError{}
	if err := utils.UnmarshalJSON(data, &fieldError, "", true, true); err == nil {
		u.FieldError = &fieldError
		u.Type = GuestPaymentsUpdateResponseBodyTypeFieldError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GuestPaymentsUpdateResponseBody", string(data))
}

func (u GuestPaymentsUpdateResponseBody) MarshalJSON() ([]byte, error) {
	if u.GenericError != nil {
		return utils.MarshalJSON(u.GenericError, "", true)
	}

	if u.FieldError != nil {
		return utils.MarshalJSON(u.FieldError, "", true)
	}

	return nil, errors.New("could not marshal union type GuestPaymentsUpdateResponseBody: all fields are null")
}

func (u GuestPaymentsUpdateResponseBody) Error() string {
	switch u.Type {
	case GuestPaymentsUpdateResponseBodyTypeGenericError:
		data, _ := json.Marshal(u.GenericError)
		return string(data)
	case GuestPaymentsUpdateResponseBodyTypeFieldError:
		data, _ := json.Marshal(u.FieldError)
		return string(data)
	default:
		return "unknown error"
	}
}
