// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// PaymentsInitializeResponseBody - The payment operation cannot complete
type PaymentsInitializeResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &PaymentsInitializeResponseBody{}

func (e *PaymentsInitializeResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
