// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/BoltApp/bolt-go/internal/utils"
	"github.com/BoltApp/bolt-go/models/components"
	"net/http"
)

type TestingCreditCardGetResponseBodyType string

const (
	TestingCreditCardGetResponseBodyTypeGenericError TestingCreditCardGetResponseBodyType = "generic-error"
	TestingCreditCardGetResponseBodyTypeFieldError   TestingCreditCardGetResponseBodyType = "field-error"
)

// TestingCreditCardGetResponseBody - An error has occurred, and further details are contained in the response
type TestingCreditCardGetResponseBody struct {
	GenericError *components.GenericError
	FieldError   *components.FieldError

	Type TestingCreditCardGetResponseBodyType

	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &TestingCreditCardGetResponseBody{}

func CreateTestingCreditCardGetResponseBodyGenericError(genericError components.GenericError) TestingCreditCardGetResponseBody {
	typ := TestingCreditCardGetResponseBodyTypeGenericError

	return TestingCreditCardGetResponseBody{
		GenericError: &genericError,
		Type:         typ,
	}
}

func CreateTestingCreditCardGetResponseBodyFieldError(fieldError components.FieldError) TestingCreditCardGetResponseBody {
	typ := TestingCreditCardGetResponseBodyTypeFieldError

	return TestingCreditCardGetResponseBody{
		FieldError: &fieldError,
		Type:       typ,
	}
}

func (u *TestingCreditCardGetResponseBody) UnmarshalJSON(data []byte) error {

	var genericError components.GenericError = components.GenericError{}
	if err := utils.UnmarshalJSON(data, &genericError, "", true, true); err == nil {
		u.GenericError = &genericError
		u.Type = TestingCreditCardGetResponseBodyTypeGenericError
		return nil
	}

	var fieldError components.FieldError = components.FieldError{}
	if err := utils.UnmarshalJSON(data, &fieldError, "", true, true); err == nil {
		u.FieldError = &fieldError
		u.Type = TestingCreditCardGetResponseBodyTypeFieldError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for TestingCreditCardGetResponseBody", string(data))
}

func (u TestingCreditCardGetResponseBody) MarshalJSON() ([]byte, error) {
	if u.GenericError != nil {
		return utils.MarshalJSON(u.GenericError, "", true)
	}

	if u.FieldError != nil {
		return utils.MarshalJSON(u.FieldError, "", true)
	}

	return nil, errors.New("could not marshal union type TestingCreditCardGetResponseBody: all fields are null")
}

func (u TestingCreditCardGetResponseBody) Error() string {
	switch u.Type {
	case TestingCreditCardGetResponseBodyTypeGenericError:
		data, _ := json.Marshal(u.GenericError)
		return string(data)
	case TestingCreditCardGetResponseBodyTypeFieldError:
		data, _ := json.Marshal(u.FieldError)
		return string(data)
	default:
		return "unknown error"
	}
}
