// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountTestPhoneData struct {
	// A random, fictitious, unassigned phone number.
	Phone string `json:"phone"`
}

func (o *AccountTestPhoneData) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}
