// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CartDiscount struct {
	// A monetary amount, i.e. a base unit amount and a supported currency.
	Amount Amount `json:"amount"`
	// Discount code.
	Code *string `json:"code,omitempty"`
	// Used to provide a link to additional details, such as a landing page, associated with the discount offering.
	DetailsURL *string `json:"details_url,omitempty"`
}

func (o *CartDiscount) GetAmount() Amount {
	if o == nil {
		return Amount{}
	}
	return o.Amount
}

func (o *CartDiscount) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *CartDiscount) GetDetailsURL() *string {
	if o == nil {
		return nil
	}
	return o.DetailsURL
}
