// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CreditCardNetwork - The credit card's network.
type CreditCardNetwork string

const (
	CreditCardNetworkVisa         CreditCardNetwork = "visa"
	CreditCardNetworkMastercard   CreditCardNetwork = "mastercard"
	CreditCardNetworkAmex         CreditCardNetwork = "amex"
	CreditCardNetworkDiscover     CreditCardNetwork = "discover"
	CreditCardNetworkJcb          CreditCardNetwork = "jcb"
	CreditCardNetworkUnionpay     CreditCardNetwork = "unionpay"
	CreditCardNetworkAlliancedata CreditCardNetwork = "alliancedata"
	CreditCardNetworkCitiplcc     CreditCardNetwork = "citiplcc"
)

func (e CreditCardNetwork) ToPointer() *CreditCardNetwork {
	return &e
}
func (e *CreditCardNetwork) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "alliancedata":
		fallthrough
	case "citiplcc":
		*e = CreditCardNetwork(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreditCardNetwork: %v", v)
	}
}
