// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ErrorTag - The type of error returned
type ErrorTag string

const (
	ErrorTagUnauthorized         ErrorTag = "unauthorized"
	ErrorTagUnprocessableRequest ErrorTag = "unprocessable_request"
	ErrorTagNotFound             ErrorTag = "not_found"
)

func (e ErrorTag) ToPointer() *ErrorTag {
	return &e
}

func (e *ErrorTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unauthorized":
		fallthrough
	case "unprocessable_request":
		fallthrough
	case "not_found":
		*e = ErrorTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorTag: %v", v)
	}
}

type Error struct {
	// The type of error returned
	DotTag ErrorTag `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (o *Error) GetDotTag() ErrorTag {
	if o == nil {
		return ErrorTag("")
	}
	return o.DotTag
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
