// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DotTag - The type of error returned
type DotTag string

const (
	DotTagUnauthorized         DotTag = "unauthorized"
	DotTagForbidden            DotTag = "forbidden"
	DotTagUnprocessableRequest DotTag = "unprocessable_request"
	DotTagNotFound             DotTag = "not_found"
)

func (e DotTag) ToPointer() *DotTag {
	return &e
}
func (e *DotTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unauthorized":
		fallthrough
	case "forbidden":
		fallthrough
	case "unprocessable_request":
		fallthrough
	case "not_found":
		*e = DotTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DotTag: %v", v)
	}
}

type GenericError struct {
	// The type of error returned
	DotTag DotTag `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (o *GenericError) GetDotTag() DotTag {
	if o == nil {
		return DotTag("")
	}
	return o.DotTag
}

func (o *GenericError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
