// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Order struct {
	// An account's identifying information.
	Profile Profile `json:"profile"`
	Cart    Cart    `json:"cart"`
}

func (o *Order) GetProfile() Profile {
	if o == nil {
		return Profile{}
	}
	return o.Profile
}

func (o *Order) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}
