// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Order struct {
	Cart    Cart    `json:"cart"`
	Profile Profile `json:"profile"`
}

func (o *Order) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *Order) GetProfile() Profile {
	if o == nil {
		return Profile{}
	}
	return o.Profile
}
