// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaymentInitializeRequest struct {
	Cart          Cart                  `json:"cart"`
	PaymentMethod PaymentMethodExtended `json:"payment_method"`
}

func (o *PaymentInitializeRequest) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *PaymentInitializeRequest) GetPaymentMethod() PaymentMethodExtended {
	if o == nil {
		return PaymentMethodExtended{}
	}
	return o.PaymentMethod
}

func (o *PaymentInitializeRequest) GetPaymentMethodID() *PaymentMethodReference {
	return o.GetPaymentMethod().PaymentMethodReference
}

func (o *PaymentInitializeRequest) GetPaymentMethodCreditCard() *PaymentMethodCreditCardInput {
	return o.GetPaymentMethod().PaymentMethodCreditCardInput
}

func (o *PaymentInitializeRequest) GetPaymentMethodPaypal() *PaymentMethodPaypal {
	return o.GetPaymentMethod().PaymentMethodPaypal
}

func (o *PaymentInitializeRequest) GetPaymentMethodAffirm() *PaymentMethodAffirm {
	return o.GetPaymentMethod().PaymentMethodAffirm
}

func (o *PaymentInitializeRequest) GetPaymentMethodAfterpay() *PaymentMethodAfterpay {
	return o.GetPaymentMethod().PaymentMethodAfterpay
}

func (o *PaymentInitializeRequest) GetPaymentMethodKlarna() *PaymentMethodKlarna {
	return o.GetPaymentMethod().PaymentMethodKlarna
}

func (o *PaymentInitializeRequest) GetPaymentMethodKlarnaAccount() *PaymentMethodKlarnaAccount {
	return o.GetPaymentMethod().PaymentMethodKlarnaAccount
}

func (o *PaymentInitializeRequest) GetPaymentMethodKlarnaPaynow() *PaymentMethodKlarnaPaynow {
	return o.GetPaymentMethod().PaymentMethodKlarnaPaynow
}
