// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DotTag string

const (
	DotTagCreditCard DotTag = "credit_card"
)

func (e DotTag) ToPointer() *DotTag {
	return &e
}
func (e *DotTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "credit_card":
		*e = DotTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DotTag: %v", v)
	}
}

type PaymentMethodCreditCard struct {
	DotTag         DotTag           `json:".tag"`
	ID             *string          `json:"id,omitempty"`
	BillingAddress AddressReference `json:"billing_address"`
	// The credit card's network.
	Network CreditCardNetwork `json:"network"`
	// The account number's last four digits.
	Last4 string `json:"last4"`
	// The expiration date, in YYYY-MM format.
	Expiration string `json:"expiration"`
}

func (o *PaymentMethodCreditCard) GetDotTag() DotTag {
	if o == nil {
		return DotTag("")
	}
	return o.DotTag
}

func (o *PaymentMethodCreditCard) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PaymentMethodCreditCard) GetBillingAddress() AddressReference {
	if o == nil {
		return AddressReference{}
	}
	return o.BillingAddress
}

func (o *PaymentMethodCreditCard) GetBillingAddressID() *AddressReferenceID {
	return o.GetBillingAddress().AddressReferenceID
}

func (o *PaymentMethodCreditCard) GetBillingAddressExplicit() *AddressReferenceExplicit {
	return o.GetBillingAddress().AddressReferenceExplicit
}

func (o *PaymentMethodCreditCard) GetNetwork() CreditCardNetwork {
	if o == nil {
		return CreditCardNetwork("")
	}
	return o.Network
}

func (o *PaymentMethodCreditCard) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *PaymentMethodCreditCard) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

type PaymentMethodCreditCardInput struct {
	DotTag         DotTag                `json:".tag"`
	BillingAddress AddressReferenceInput `json:"billing_address"`
	// The credit card's network.
	Network CreditCardNetwork `json:"network"`
	// The Bank Identification Number (BIN). This is typically the first 4 to 6 digits of the account number.
	Bin string `json:"bin"`
	// The account number's last four digits.
	Last4 string `json:"last4"`
	// The expiration date, in YYYY-MM format.
	Expiration string `json:"expiration"`
	// The Bolt token associated with the credit card.
	Token string `json:"token"`
}

func (o *PaymentMethodCreditCardInput) GetDotTag() DotTag {
	if o == nil {
		return DotTag("")
	}
	return o.DotTag
}

func (o *PaymentMethodCreditCardInput) GetBillingAddress() AddressReferenceInput {
	if o == nil {
		return AddressReferenceInput{}
	}
	return o.BillingAddress
}

func (o *PaymentMethodCreditCardInput) GetBillingAddressID() *AddressReferenceID {
	return o.GetBillingAddress().AddressReferenceID
}

func (o *PaymentMethodCreditCardInput) GetBillingAddressExplicit() *AddressReferenceExplicitInput {
	return o.GetBillingAddress().AddressReferenceExplicitInput
}

func (o *PaymentMethodCreditCardInput) GetNetwork() CreditCardNetwork {
	if o == nil {
		return CreditCardNetwork("")
	}
	return o.Network
}

func (o *PaymentMethodCreditCardInput) GetBin() string {
	if o == nil {
		return ""
	}
	return o.Bin
}

func (o *PaymentMethodCreditCardInput) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *PaymentMethodCreditCardInput) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *PaymentMethodCreditCardInput) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
