// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type PaymentMethodKlarnaAccountTag string

const (
	PaymentMethodKlarnaAccountTagKlarnaAccount PaymentMethodKlarnaAccountTag = "klarna_account"
)

func (e PaymentMethodKlarnaAccountTag) ToPointer() *PaymentMethodKlarnaAccountTag {
	return &e
}
func (e *PaymentMethodKlarnaAccountTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "klarna_account":
		*e = PaymentMethodKlarnaAccountTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethodKlarnaAccountTag: %v", v)
	}
}

type PaymentMethodKlarnaAccountOutput struct {
	DotTag PaymentMethodKlarnaAccountTag `json:".tag"`
}

func (o *PaymentMethodKlarnaAccountOutput) GetDotTag() PaymentMethodKlarnaAccountTag {
	if o == nil {
		return PaymentMethodKlarnaAccountTag("")
	}
	return o.DotTag
}

type PaymentMethodKlarnaAccount struct {
	DotTag PaymentMethodKlarnaAccountTag `json:".tag"`
	// Return URL to return to after payment completion in Klarna.
	ReturnURL string `json:"return_url"`
}

func (o *PaymentMethodKlarnaAccount) GetDotTag() PaymentMethodKlarnaAccountTag {
	if o == nil {
		return PaymentMethodKlarnaAccountTag("")
	}
	return o.DotTag
}

func (o *PaymentMethodKlarnaAccount) GetReturnURL() string {
	if o == nil {
		return ""
	}
	return o.ReturnURL
}
