// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProcessorResponse - Raw authorization response from the payment processor
type ProcessorResponse struct {
	ContentType *string `json:"content_type,omitempty"`
	APIVersion  *string `json:"api_version,omitempty"`
	Text        *string `json:"text,omitempty"`
}

func (o *ProcessorResponse) GetContentType() *string {
	if o == nil {
		return nil
	}
	return o.ContentType
}

func (o *ProcessorResponse) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

func (o *ProcessorResponse) GetText() *string {
	if o == nil {
		return nil
	}
	return o.Text
}
