// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ProfileCreationData struct {
	// Whether or not an account should be created.
	CreateAccount bool `json:"create_account"`
	// The given name of the person associated with this profile.
	FirstName string `json:"first_name"`
	// The last name of the person associated with this profile.
	LastName string `json:"last_name"`
	// The email address asscoiated with this profile.
	Email string `json:"email"`
	// The phone number associated with this profile.
	Phone *string `json:"phone,omitempty"`
}

func (o *ProfileCreationData) GetCreateAccount() bool {
	if o == nil {
		return false
	}
	return o.CreateAccount
}

func (o *ProfileCreationData) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *ProfileCreationData) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *ProfileCreationData) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *ProfileCreationData) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}
