// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Profile struct {
	// The given name of the person associated with this profile.
	FirstName string `json:"first_name"`
	// The last name of the person associated with this profile.
	LastName string `json:"last_name"`
	// The email address asscoiated with this profile.
	Email string `json:"email"`
	// The phone number associated with this profile.
	Phone *string `json:"phone,omitempty"`
}

func (o *Profile) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *Profile) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *Profile) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *Profile) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}
