// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Security struct {
	APIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
	Oauth  *string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *Security) GetOauth() *string {
	if o == nil {
		return nil
	}
	return o.Oauth
}
