// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionAuthorization struct {
	ProcessorReference *string `json:"processor_reference,omitempty"`
	// Raw authorization response from the payment processor
	ProcessorResponse *ProcessorResponse `json:"processor_response,omitempty"`
}

func (o *TransactionAuthorization) GetProcessorReference() *string {
	if o == nil {
		return nil
	}
	return o.ProcessorReference
}

func (o *TransactionAuthorization) GetProcessorResponse() *ProcessorResponse {
	if o == nil {
		return nil
	}
	return o.ProcessorResponse
}
