// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionAuthorization struct {
	ProcessorReference *string `json:"processor_reference,omitempty"`
}

func (o *TransactionAuthorization) GetProcessorReference() *string {
	if o == nil {
		return nil
	}
	return o.ProcessorReference
}
