// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Transaction struct {
	Reference *string `json:"reference,omitempty"`
	// Payment authorization events attached to a transaction
	Authorizations []TransactionAuthorization `json:"authorizations,omitempty"`
}

func (o *Transaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *Transaction) GetAuthorizations() []TransactionAuthorization {
	if o == nil {
		return nil
	}
	return o.Authorizations
}
