workflowVersion: 1.0.0
sources:
    bolt-go-api:
        inputs:
            - location: https://api-docs.bolt.com/api.bundle.yaml
        overlays:
            - location: ./generic_error_overlay.yaml
targets:
    bolt-go-sdk:
        target: go
        source: bolt-go-api
