workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://api-docs.bolt.com/api.bundle.yaml
        overlays:
            - ./default_error_overlay.yaml
targets:
    bolt-go:
        target: go
        source: my-source
